<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class LocalizacionesSeeder extends Seeder
{
    public function run(): void
    {
        $localizaciones = [
            ['id' => 1, 'nombre' => 'Fisico-quimico', 'id_area' => 'cca'],
            ['id' => 2, 'nombre' => 'Oficina', 'id_area' => 'sis'],
            ['id' => 3, 'nombre' => 'Deposito', 'id_area' => 'sis'],
            ['id' => 4, 'nombre' => 'Oficina', 'id_area' => 'com'],
            ['id' => 5, 'nombre' => 'Oficina', 'id_area' => 'asr'],
            ['id' => 6, 'nombre' => 'Material limpio', 'id_area' => 'lse'],
            ['id' => 7, 'nombre' => 'Elaboración', 'id_area' => 'lse'],
            ['id' => 8, 'nombre' => 'Fraccionamiento 1', 'id_area' => 'lse'],
            ['id' => 11, 'nombre' => 'Fraccionamiento de pequños volúmenes', 'id_area' => 'lsn'],
            ['id' => 12, 'nombre' => 'Preparación de soluciones', 'id_area' => 'lsn'],
            ['id' => 13, 'nombre' => 'Blisteado 3', 'id_area' => 'sol'],
            ['id' => 14, 'nombre' => 'Depósito de material limpio', 'id_area' => 'lse'],
            ['id' => 15, 'nombre' => 'Fraccionamiento de semisólidos', 'id_area' => 'lsn'],
            ['id' => 16, 'nombre' => 'Acondicionamiento 3', 'id_area' => 'aco'],
            ['id' => 17, 'nombre' => 'Pasillo de granulado', 'id_area' => 'sol'],
            ['id' => 18, 'nombre' => 'Fraccionamiento de grandes volúmenes', 'id_area' => 'lsn'],
            ['id' => 19, 'nombre' => 'Acondicionamiento 5', 'id_area' => 'aco'],
            ['id' => 20, 'nombre' => 'Acondicionamiento 8', 'id_area' => 'aco'],
            ['id' => 21, 'nombre' => 'Elaboración', 'id_area' => 'lsn'],
            ['id' => 22, 'nombre' => 'Línea de Aire comprimido- Box 1', 'id_area' => 'sol'],
            ['id' => 23, 'nombre' => 'Elaboración - Linea de nitrogeno', 'id_area' => 'lse'],
            ['id' => 24, 'nombre' => 'Preparación de materiales', 'id_area' => 'lse'],
            ['id' => 25, 'nombre' => 'Ensobrado', 'id_area' => 'sol'],
            ['id' => 26, 'nombre' => 'Box 2', 'id_area' => 'sol'],
            ['id' => 27, 'nombre' => 'Acondicionamiento 6', 'id_area' => 'aco'],
            ['id' => 29, 'nombre' => 'Sellado', 'id_area' => 'sol'],
            ['id' => 30, 'nombre' => 'Moldeo', 'id_area' => 'sol'],
            ['id' => 31, 'nombre' => 'Mezclado', 'id_area' => 'sol'],
            ['id' => 32, 'nombre' => 'Granulado', 'id_area' => 'sol'],
            ['id' => 33, 'nombre' => 'Elaboracion de liquidos', 'id_area' => 'lsn'],
            ['id' => 34, 'nombre' => 'Acondicionamiento 4', 'id_area' => 'aco'],
            ['id' => 35, 'nombre' => 'Fraccionamiento 2', 'id_area' => 'lse'],
            ['id' => 36, 'nombre' => 'deposito', 'id_area' => 'com'],
            ['id' => 37, 'nombre' => 'Cámara - Zona de Carga', 'id_area' => 'mic'],
            ['id' => 38, 'nombre' => 'Camara de Estabilidad', 'id_area' => 'cca'],
            ['id' => 39, 'nombre' => 'Control Higienico Planta baja.', 'id_area' => 'mic'],
            ['id' => 40, 'nombre' => 'Esterilidades', 'id_area' => 'mic'],
            ['id' => 41, 'nombre' => 'Control Higiénico', 'id_area' => 'mic'],
            ['id' => 42, 'nombre' => 'Estabilidades', 'id_area' => 'cca'],
            ['id' => 43, 'nombre' => 'Cepario', 'id_area' => 'mic'],
            ['id' => 44, 'nombre' => 'Lavadero - Linea aire comprimido', 'id_area' => 'lse'],
            ['id' => 45, 'nombre' => 'Ensobrado', 'id_area' => 'sol'],
            ['id' => 46, 'nombre' => 'Compresión - Box 1', 'id_area' => 'sol'],
            ['id' => 47, 'nombre' => 'Compresión', 'id_area' => 'sol'],
            ['id' => 48, 'nombre' => 'Recubrimiento', 'id_area' => 'sol'],
            ['id' => 49, 'nombre' => 'Empaque X', 'id_area' => 'aco'],
            ['id' => 50, 'nombre' => 'Descarga', 'id_area' => 'lse'],
            ['id' => 51, 'nombre' => 'Acondicionamiento 7', 'id_area' => 'aco'],
            ['id' => 52, 'nombre' => 'Lavadero - Punto de burbuja', 'id_area' => 'lse'],
            ['id' => 53, 'nombre' => 'Esclusa intermedia entre Fraccionamiento 1 y Elaboración', 'id_area' => 'lse'],
            ['id' => 54, 'nombre' => 'Fraccionamiento de Semisólidos 2', 'id_area' => 'lsn'],
            ['id' => 55, 'nombre' => 'Lavadero', 'id_area' => 'lse'],
            ['id' => 56, 'nombre' => 'Box 4', 'id_area' => 'sol'],
            ['id' => 57, 'nombre' => 'Fraccionamiento 1 - Linea de Nitrógeno', 'id_area' => 'lse'],
            ['id' => 58, 'nombre' => 'Fraccionamiento 2 - Línea de aire comprimido', 'id_area' => 'lse'],
            ['id' => 59, 'nombre' => 'Mezclado 2', 'id_area' => 'sol'],
            ['id' => 60, 'nombre' => 'Sala de Pesadas', 'id_area' => 'pes'],
            ['id' => 61, 'nombre' => 'Acondicionamiento 10', 'id_area' => 'aco'],
            ['id' => 62, 'nombre' => 'Recubrimiento 2', 'id_area' => 'sol'],
            ['id' => 63, 'nombre' => 'Box 6 - Compresión', 'id_area' => 'sol'],
            ['id' => 64, 'nombre' => 'Blisteado 2', 'id_area' => 'sol'],
            ['id' => 65, 'nombre' => 'Empaque 9 - Box 2', 'id_area' => 'aco'],
            ['id' => 66, 'nombre' => 'Sector sur', 'id_area' => 'pex'],
            ['id' => 67, 'nombre' => 'Exterior sala de máquinas 1', 'id_area' => 'sm1'],
            ['id' => 68, 'nombre' => 'Exterior sala de máquinas 1', 'id_area' => 'sm1'],
            ['id' => 69, 'nombre' => 'Planta de Tratamiento de Agua', 'id_area' => 'sm1'],
            ['id' => 70, 'nombre' => 'Muestreo', 'id_area' => 'cca'],
            ['id' => 71, 'nombre' => 'Cámara - Zona de Carga', 'id_area' => 'cca'],
            ['id' => 72, 'nombre' => 'Acondicionamiento 2', 'id_area' => 'aco'],
            ['id' => 73, 'nombre' => 'Acondicionamiento 9', 'id_area' => 'aco'],
            ['id' => 74, 'nombre' => 'Depósito de inflamables', 'id_area' => 'der'],
            ['id' => 75, 'nombre' => 'Secado', 'id_area' => 'sol'],
            ['id' => 76, 'nombre' => 'Blisteado', 'id_area' => 'sol'],
            ['id' => 77, 'nombre' => 'Encapsulado', 'id_area' => 'sol'],
            ['id' => 78, 'nombre' => 'Box 1', 'id_area' => 'sol'],
            ['id' => 79, 'nombre' => 'Box 3', 'id_area' => 'sol'],
            ['id' => 80, 'nombre' => 'Paila', 'id_area' => 'sol'],
            ['id' => 81, 'nombre' => 'Elaboración - Línea de vapor', 'id_area' => 'lse'],
            ['id' => 82, 'nombre' => 'Fraccionamiento 1 - Línea de aire comprimido', 'id_area' => 'lse'],
            ['id' => 83, 'nombre' => 'Elaboracion semisolidos', 'id_area' => 'lsn'],
            ['id' => 84, 'nombre' => '2do piso planta', 'id_area' => 'sm1'],
            ['id' => 85, 'nombre' => 'Entrepiso', 'id_area' => 'sm3'],
            ['id' => 86, 'nombre' => 'Exterior de sala de máquinas 2', 'id_area' => 'sm2'],
            ['id' => 87, 'nombre' => 'Exterior, debajo de escalera de acceso', 'id_area' => 'sm1'],
            ['id' => 88, 'nombre' => 'Exterior, sector sur de la empresa', 'id_area' => 'ext'],
            ['id' => 89, 'nombre' => 'Playon Exterior Sector sur de la empresa', 'id_area' => 'ext'],
            ['id' => 90, 'nombre' => 'Terraza técnica 1', 'id_area' => 'sm2'],
            ['id' => 91, 'nombre' => 'Terraza técnica 3', 'id_area' => 'sm2'],
            ['id' => 92, 'nombre' => 'Expedición', 'id_area' => 'dee'],
            ['id' => 93, 'nombre' => 'Materia Prima', 'id_area' => 'der'],
            ['id' => 94, 'nombre' => 'Material de empaque', 'id_area' => 'der'],
            ['id' => 95, 'nombre' => 'Materia prima aprobada', 'id_area' => 'der'],
            ['id' => 96, 'nombre' => 'Picking', 'id_area' => 'dee'],
            ['id' => 97, 'nombre' => 'Pre cámara/ Producto terminado', 'id_area' => 'dee'],
            ['id' => 98, 'nombre' => 'Producto terminado', 'id_area' => 'dee'],
            ['id' => 99, 'nombre' => 'Recepción de materiales', 'id_area' => 'der'],
            ['id' => 100, 'nombre' => 'Lavadero', 'id_area' => 'mae'],
            ['id' => 101, 'nombre' => 'Comedor', 'id_area' => 'mae'],
            ['id' => 103, 'nombre' => 'Material de empaque 3', 'id_area' => 'der'],
            ['id' => 104, 'nombre' => 'Mezclado y tamizado', 'id_area' => 'sol'],
            ['id' => 105, 'nombre' => 'Material de empaque 2', 'id_area' => 'der'],
            ['id' => 106, 'nombre' => 'Contramuestras', 'id_area' => 'cca'],
            ['id' => 107, 'nombre' => 'Contramuestra materia prima', 'id_area' => 'cca'],
            ['id' => 109, 'nombre' => 'Contramuestra producto termiando 2', 'id_area' => 'cca'],
            ['id' => 110, 'nombre' => 'Packaging 2', 'id_area' => 'dee'],
            ['id' => 111, 'nombre' => 'Otro', 'id_area' => 'aco'],
            ['id' => 112, 'nombre' => 'Otro', 'id_area' => 'act'],
            ['id' => 113, 'nombre' => 'Otro', 'id_area' => 'ari'],
            ['id' => 114, 'nombre' => 'Otro', 'id_area' => 'asr'],
            ['id' => 115, 'nombre' => 'Otro', 'id_area' => 'cca'],
            ['id' => 116, 'nombre' => 'Otro', 'id_area' => 'coe'],
            ['id' => 117, 'nombre' => 'Otro', 'id_area' => 'com'],
            ['id' => 118, 'nombre' => 'Otro', 'id_area' => 'con'],
            ['id' => 119, 'nombre' => 'Otro', 'id_area' => 'cos'],
            ['id' => 120, 'nombre' => 'Otro', 'id_area' => 'dee'],
            ['id' => 121, 'nombre' => 'Otro', 'id_area' => 'der'],
            ['id' => 122, 'nombre' => 'Otro', 'id_area' => 'des'],
            ['id' => 123, 'nombre' => 'Otro', 'id_area' => 'dir'],
            ['id' => 124, 'nombre' => 'Otro', 'id_area' => 'dis'],
            ['id' => 125, 'nombre' => 'Otro', 'id_area' => 'dit'],
            ['id' => 126, 'nombre' => 'Otro', 'id_area' => 'dmp'],
            ['id' => 127, 'nombre' => 'Otro', 'id_area' => 'dse'],
            ['id' => 128, 'nombre' => 'Otro', 'id_area' => 'ext'],
            ['id' => 129, 'nombre' => 'Otro', 'id_area' => 'fac'],
            ['id' => 130, 'nombre' => 'Otro', 'id_area' => 'gca'],
            ['id' => 131, 'nombre' => 'Otro', 'id_area' => 'GSP'],
            ['id' => 132, 'nombre' => 'Otro', 'id_area' => 'gua'],
            ['id' => 133, 'nombre' => 'Otro', 'id_area' => 'ind'],
            ['id' => 134, 'nombre' => 'Otro', 'id_area' => 'ing'],
            ['id' => 135, 'nombre' => 'Otro', 'id_area' => 'lnt'],
            ['id' => 136, 'nombre' => 'Otro', 'id_area' => 'lse'],
            ['id' => 137, 'nombre' => 'Otro', 'id_area' => 'lsn'],
            ['id' => 138, 'nombre' => 'Otro', 'id_area' => 'lst'],
            ['id' => 139, 'nombre' => 'Otro', 'id_area' => 'mae'],
            ['id' => 140, 'nombre' => 'Otro', 'id_area' => 'man'],
            ['id' => 141, 'nombre' => 'Otro', 'id_area' => 'mar'],
            ['id' => 142, 'nombre' => 'Otro', 'id_area' => 'med'],
            ['id' => 143, 'nombre' => 'Otro', 'id_area' => 'mic'],
            ['id' => 144, 'nombre' => 'Otro', 'id_area' => 'oft'],
            ['id' => 145, 'nombre' => 'Otro', 'id_area' => 'ope'],
            ['id' => 146, 'nombre' => 'Otro', 'id_area' => 'pag'],
            ['id' => 147, 'nombre' => 'Otro', 'id_area' => 'per'],
            ['id' => 148, 'nombre' => 'Otro', 'id_area' => 'pes'],
            ['id' => 149, 'nombre' => 'Otro', 'id_area' => 'pex'],
            ['id' => 150, 'nombre' => 'Otro', 'id_area' => 'pla'],
            ['id' => 151, 'nombre' => 'Otro', 'id_area' => 'pre'],
            ['id' => 152, 'nombre' => 'Otro', 'id_area' => 'pro'],
            ['id' => 153, 'nombre' => 'Otro', 'id_area' => 'rec'],
            ['id' => 154, 'nombre' => 'Otro', 'id_area' => 'reh'],
            ['id' => 155, 'nombre' => 'Otro', 'id_area' => 'sis'],
            ['id' => 156, 'nombre' => 'Otro', 'id_area' => 'sm1'],
            ['id' => 157, 'nombre' => 'Otro', 'id_area' => 'sm2'],
            ['id' => 158, 'nombre' => 'Otro', 'id_area' => 'sm3'],
            ['id' => 159, 'nombre' => 'Otro', 'id_area' => 'sol'],
            ['id' => 160, 'nombre' => 'Otro', 'id_area' => 'sot'],
            ['id' => 161, 'nombre' => 'Otro', 'id_area' => 'srs'],
            ['id' => 162, 'nombre' => 'Otro', 'id_area' => 'tt1'],
            ['id' => 163, 'nombre' => 'Otro', 'id_area' => 'tt2'],
            ['id' => 164, 'nombre' => 'Otro', 'id_area' => 'val'],
            ['id' => 165, 'nombre' => 'Otro', 'id_area' => 'ven'],
            ['id' => 166, 'nombre' => 'Oficina', 'id_area' => 'aco'],
            ['id' => 167, 'nombre' => 'Oficina 1', 'id_area' => 'cca'],
            ['id' => 168, 'nombre' => 'Oficina 2', 'id_area' => 'cca'],
            ['id' => 169, 'nombre' => 'Oficina', 'id_area' => 'coe'],
            ['id' => 170, 'nombre' => 'Oficina', 'id_area' => 'con'],
            ['id' => 171, 'nombre' => 'Oficina', 'id_area' => 'cos'],
            ['id' => 172, 'nombre' => 'Oficina', 'id_area' => 'dir'],
            ['id' => 173, 'nombre' => 'Oficina', 'id_area' => 'dis'],
            ['id' => 174, 'nombre' => 'Oficina', 'id_area' => 'dit'],
            ['id' => 175, 'nombre' => 'Oficina', 'id_area' => 'fac'],
            ['id' => 176, 'nombre' => 'Oficina', 'id_area' => 'gca'],
            ['id' => 177, 'nombre' => 'Oficina', 'id_area' => 'GSP'],
            ['id' => 178, 'nombre' => 'Oficina', 'id_area' => 'gua'],
            ['id' => 179, 'nombre' => 'Oficina', 'id_area' => 'ind'],
            ['id' => 180, 'nombre' => 'Oficina', 'id_area' => 'ing'],
            ['id' => 181, 'nombre' => 'Oficina', 'id_area' => 'mae'],
            ['id' => 182, 'nombre' => 'Sala vidriada 1', 'id_area' => 'srs'],
            ['id' => 183, 'nombre' => 'Sala vidriada 2', 'id_area' => 'srs'],
            ['id' => 184, 'nombre' => 'Sala de reuniones', 'id_area' => 'srs'],
            ['id' => 185, 'nombre' => 'Pasillo', 'id_area' => 'lse'],
            ['id' => 186, 'nombre' => 'Elaboracion', 'id_area' => 'oft'],
            ['id' => 187, 'nombre' => 'Oficina', 'id_area' => 'adm'],
            ['id' => 188, 'nombre' => 'Oficina planta baja', 'id_area' => 'adm'],
            ['id' => 189, 'nombre' => 'Oficina', 'id_area' => 'pro'],
            ['id' => 190, 'nombre' => 'Oficina', 'id_area' => 'des'],
            ['id' => 191, 'nombre' => 'Sala de servidor (administracion)', 'id_area' => 'sis'],
            ['id' => 192, 'nombre' => 'Sala de comunicaciones (planta)', 'id_area' => 'sis'],
            ['id' => 194, 'nombre' => 'Oficina', 'id_area' => 'med'],
            ['id' => 195, 'nombre' => 'Control de materiales', 'id_area' => 'cca'],
            ['id' => 196, 'nombre' => 'Oficina', 'id_area' => 'der'],
            ['id' => 197, 'nombre' => 'Oficina', 'id_area' => 'dee'],
            ['id' => 198, 'nombre' => 'Oficina', 'id_area' => 'gpr'],
            ['id' => 199, 'nombre' => 'Otro', 'id_area' => 'gpr'],
            ['id' => 200, 'nombre' => 'Oficina', 'id_area' => 'lsn'],
            ['id' => 201, 'nombre' => 'Oficina', 'id_area' => 'man'],
            ['id' => 202, 'nombre' => 'Oficina', 'id_area' => 'mar'],
            ['id' => 203, 'nombre' => 'Oficina', 'id_area' => 'mic'],
            ['id' => 204, 'nombre' => 'Oficina', 'id_area' => 'oft'],
            ['id' => 205, 'nombre' => 'Oficina', 'id_area' => 'pag'],
            ['id' => 206, 'nombre' => 'Oficina planta baja', 'id_area' => 'pag'],
            ['id' => 207, 'nombre' => 'Pasillo', 'id_area' => 'oft'],
            ['id' => 208, 'nombre' => 'Oficina', 'id_area' => 'per'],
            ['id' => 209, 'nombre' => 'Oficina', 'id_area' => 'pla'],
            ['id' => 210, 'nombre' => 'Oficina', 'id_area' => 'pre'],
            ['id' => 211, 'nombre' => 'Oficina', 'id_area' => 'rec'],
            ['id' => 212, 'nombre' => 'Oficina', 'id_area' => 'reh'],
            ['id' => 213, 'nombre' => 'Oficina', 'id_area' => 'sol'],
            ['id' => 214, 'nombre' => 'Oficina', 'id_area' => 'val'],
            ['id' => 215, 'nombre' => 'Oficina', 'id_area' => 'ven'],
            ['id' => 216, 'nombre' => 'Oficina', 'id_area' => 'vic']
        ];

        DB::table('localizaciones')->insert($localizaciones);
    }
}
