<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class TiposEquiposSeeder extends Seeder
{
    public function run(): void
    {
        $tipos = [
            ['id' => 0, 'nombre' => 'Edilicio'],
            ['id' => 1, 'nombre' => 'Ablandador'],
            ['id' => 2, 'nombre' => 'Acomodador de frascos'],
            ['id' => 3, 'nombre' => 'Agitador'],
            ['id' => 4, 'nombre' => 'Agitador con placa calefactora'],
            ['id' => 5, 'nombre' => 'Agitador Externo con Tolva'],
            ['id' => 6, 'nombre' => 'Agitador magnético'],
            ['id' => 7, 'nombre' => 'Agitador multipunto'],
            ['id' => 8, 'nombre' => 'Aire acondicionado'],
            ['id' => 9, 'nombre' => 'Alimantador'],
            ['id' => 10, 'nombre' => 'Alimentador de frascos'],
            ['id' => 11, 'nombre' => 'Amasadora'],
            ['id' => 12, 'nombre' => 'Analizador de humedad'],
            ['id' => 13, 'nombre' => 'Analizador de integridad de filtros'],
            ['id' => 14, 'nombre' => 'Analizador de TOC'],
            ['id' => 15, 'nombre' => 'Analizador de TOC en línea'],
            ['id' => 16, 'nombre' => 'Anemómetro'],
            ['id' => 17, 'nombre' => 'Apilador'],
            ['id' => 18, 'nombre' => 'Aspiradora'],
            ['id' => 19, 'nombre' => 'Autoclave'],
            ['id' => 20, 'nombre' => 'Autoclave por vapor de agua'],
            ['id' => 21, 'nombre' => 'Autoelevador'],
            ['id' => 22, 'nombre' => 'Autoelevador eléctrico'],
            ['id' => 23, 'nombre' => 'Balanza'],
            ['id' => 24, 'nombre' => 'Balanza analítica'],
            ['id' => 25, 'nombre' => 'Balanza contadora'],
            ['id' => 26, 'nombre' => 'Balanza Granataria'],
            ['id' => 27, 'nombre' => 'Balanza Ohaus'],
            ['id' => 28, 'nombre' => 'Baño de ultrasonido'],
            ['id' => 29, 'nombre' => 'Baño seco digital'],
            ['id' => 30, 'nombre' => 'Baño termostático'],
            ['id' => 31, 'nombre' => 'Bidón'],
            ['id' => 32, 'nombre' => 'Blistera'],
            ['id' => 33, 'nombre' => 'Bomba centrífuga'],
            ['id' => 34, 'nombre' => 'Bomba de vacio'],
            ['id' => 35, 'nombre' => 'Bomba Dosificadora Volumetrica'],
            ['id' => 36, 'nombre' => 'Bomba neumática'],
            ['id' => 37, 'nombre' => 'Bomba neumatica de doble diafragma'],
            ['id' => 38, 'nombre' => 'Bomba peristáltica'],
            ['id' => 39, 'nombre' => 'Bomba peristaltica sanitaria'],
            ['id' => 40, 'nombre' => 'Bomba tornillo'],
            ['id' => 41, 'nombre' => 'Brazo robotico'],
            ['id' => 42, 'nombre' => 'Bureta'],
            ['id' => 43, 'nombre' => 'Cabina de seguridad'],
            ['id' => 44, 'nombre' => 'Cabinas flujos laminares'],
            ['id' => 45, 'nombre' => 'Caldera'],
            ['id' => 46, 'nombre' => 'Calderín de SIP'],
            ['id' => 47, 'nombre' => 'Calefactor'],
            ['id' => 48, 'nombre' => 'Calibrador molino oscilante'],
            ['id' => 49, 'nombre' => 'Calibre'],
            ['id' => 50, 'nombre' => 'Calibre Digital'],
            ['id' => 51, 'nombre' => 'Cámara de Estabilidad'],
            ['id' => 52, 'nombre' => 'Cámara frigorífica'],
            ['id' => 53, 'nombre' => 'Campana de extracción'],
            ['id' => 54, 'nombre' => 'Cargador de baterias'],
            ['id' => 55, 'nombre' => 'Cargador de polvo'],
            ['id' => 56, 'nombre' => 'cargador universal'],
            ['id' => 57, 'nombre' => 'Centrifuga'],
            ['id' => 58, 'nombre' => 'Chiller'],
            ['id' => 59, 'nombre' => 'Cinta transportadora'],
            ['id' => 60, 'nombre' => 'Codificadora'],
            ['id' => 61, 'nombre' => 'Codificadora inkjet'],
            ['id' => 62, 'nombre' => 'Codificadora/ etiquetadora'],
            ['id' => 63, 'nombre' => 'Colector de polvo'],
            ['id' => 64, 'nombre' => 'Colorímetro'],
            ['id' => 65, 'nombre' => 'Compresor de aire'],
            ['id' => 66, 'nombre' => 'Compresora'],
            ['id' => 67, 'nombre' => 'Conductimetro'],
            ['id' => 68, 'nombre' => 'Contador de colonias'],
            ['id' => 69, 'nombre' => 'Contador de partículas'],
            ['id' => 70, 'nombre' => 'Contenedor de bolsas estériles descartables'],
            ['id' => 71, 'nombre' => 'Controlador de agua purificada'],
            ['id' => 72, 'nombre' => 'Controlador de comprimidos / Tablet Tester'],
            ['id' => 73, 'nombre' => 'Cromatógrafo'],
            ['id' => 74, 'nombre' => 'Curban'],
            ['id' => 75, 'nombre' => 'Desblisteadora Manual'],
            ['id' => 76, 'nombre' => 'Desempolvador'],
            ['id' => 77, 'nombre' => 'Deshumectador'],
            ['id' => 78, 'nombre' => 'Deshumidificador'],
            ['id' => 79, 'nombre' => 'Deshumidificador/ Secador por absorción'],
            ['id' => 80, 'nombre' => 'Desintegrador'],
            ['id' => 81, 'nombre' => 'Determinador de granulometría'],
            ['id' => 82, 'nombre' => 'Disgregador'],
            ['id' => 83, 'nombre' => 'Disolutor'],
            ['id' => 84, 'nombre' => 'Dobladora de prospectos'],
            ['id' => 85, 'nombre' => 'Dosificadora'],
            ['id' => 86, 'nombre' => 'Dosificadora de frascos goteros'],
            ['id' => 87, 'nombre' => 'Dosificadora de polvo'],
            ['id' => 88, 'nombre' => 'Dosificadora peristaltica (Bomba)'],
            ['id' => 89, 'nombre' => 'Durómetro'],
            ['id' => 90, 'nombre' => 'Zorra balanza'],
            ['id' => 91, 'nombre' => 'Elevador de tambores'],
            ['id' => 92, 'nombre' => 'Emulsificadora'],
            ['id' => 93, 'nombre' => 'Encapsuladora'],
            ['id' => 94, 'nombre' => 'Encintadora'],
            ['id' => 95, 'nombre' => 'Encintadora / Sistema de etiquetado de sticker de seguridad'],
            ['id' => 96, 'nombre' => 'Ensobradora'],
            ['id' => 97, 'nombre' => 'Envasadora al Vacio y Selladora'],
            ['id' => 98, 'nombre' => 'Equipo agua Purificada'],
            ['id' => 99, 'nombre' => 'Equipo Multiproposito'],
            ['id' => 100, 'nombre' => 'Escalera'],
            ['id' => 101, 'nombre' => 'Espátula'],
            ['id' => 102, 'nombre' => 'Espatula de Acero Inoxidable'],
            ['id' => 103, 'nombre' => 'Espatula de Goma'],
            ['id' => 104, 'nombre' => 'Espátula de teflón grande'],
            ['id' => 105, 'nombre' => 'Espectrofotómetro'],
            ['id' => 106, 'nombre' => 'Espectrofotómetro UV-visible'],
            ['id' => 107, 'nombre' => 'Espectrometro Raman'],
            ['id' => 108, 'nombre' => 'Esterilizador'],
            ['id' => 109, 'nombre' => 'Estuchadora'],
            ['id' => 110, 'nombre' => 'Estufa'],
            ['id' => 111, 'nombre' => 'Estufa de cultivo'],
            ['id' => 112, 'nombre' => 'Estufa de estabilidad'],
            ['id' => 113, 'nombre' => 'Estufa de esterilización'],
            ['id' => 114, 'nombre' => 'Estufa de secado'],
            ['id' => 115, 'nombre' => 'Etiquetadora'],
            ['id' => 116, 'nombre' => 'Evaporador de aire acondicionado'],
            ['id' => 117, 'nombre' => 'Extractor a fuga'],
            ['id' => 118, 'nombre' => 'Extractor de aire'],
            ['id' => 119, 'nombre' => 'Extractor de polvos'],
            ['id' => 120, 'nombre' => 'Fiabrilómetro'],
            ['id' => 121, 'nombre' => 'Filtro'],
            ['id' => 122, 'nombre' => 'Filtro prensa'],
            ['id' => 123, 'nombre' => 'FITR (infrarojo)'],
            ['id' => 124, 'nombre' => 'Flujo laminar'],
            ['id' => 125, 'nombre' => 'Fraccionadora'],
            ['id' => 126, 'nombre' => 'Fraccionadora de alcohol'],
            ['id' => 127, 'nombre' => 'Fraccionadora de pomos'],
            ['id' => 128, 'nombre' => 'Freezer'],
            ['id' => 129, 'nombre' => 'Friabilometro'],
            ['id' => 130, 'nombre' => 'Fundidor de grasa'],
            ['id' => 131, 'nombre' => 'Generador de vacío'],
            ['id' => 132, 'nombre' => 'Granulador'],
            ['id' => 133, 'nombre' => 'Grupo electrógeno'],
            ['id' => 134, 'nombre' => 'Heladera'],
            ['id' => 135, 'nombre' => 'Homomixer'],
            ['id' => 136, 'nombre' => 'Horno termocontraible'],
            ['id' => 137, 'nombre' => 'HPLC'],
            ['id' => 138, 'nombre' => 'Impresora'],
            ['id' => 139, 'nombre' => 'Inductor'],
            ['id' => 140, 'nombre' => 'Inflador de bolsas de embalaje'],
            ['id' => 141, 'nombre' => 'Isolator'],
            ['id' => 142, 'nombre' => 'Jarra de acero inoxidable'],
            ['id' => 143, 'nombre' => 'Jarra Graduada'],
            ['id' => 144, 'nombre' => 'Lámpara UV'],
            ['id' => 145, 'nombre' => 'Lavadora de pisos'],
            ['id' => 146, 'nombre' => 'Lavadora ultrasónica'],
            ['id' => 147, 'nombre' => 'Lavarropas'],
            ['id' => 148, 'nombre' => 'Lavasecadora fregadora de pisos'],
            ['id' => 149, 'nombre' => 'Licuadora de mano'],
            ['id' => 150, 'nombre' => 'Llenadora de Envases Peristáltica'],
            ['id' => 151, 'nombre' => 'Llenadora de polvos A.M.S'],
            ['id' => 152, 'nombre' => 'Llenadora de viales plásticos'],
            ['id' => 153, 'nombre' => 'Lustradora'],
            ['id' => 154, 'nombre' => 'Luz inactínica'],
            ['id' => 155, 'nombre' => 'Manifold de Acero inoxidable x 4'],
            ['id' => 156, 'nombre' => 'Manifold FINO'],
            ['id' => 157, 'nombre' => 'Manifold Fino x 6'],
            ['id' => 158, 'nombre' => 'Manifold x 4 racord'],
            ['id' => 159, 'nombre' => 'Manifold x 5 racord'],
            ['id' => 160, 'nombre' => 'Manómetro'],
            ['id' => 161, 'nombre' => 'Manovacuómetro'],
            ['id' => 162, 'nombre' => 'Masa revisadora'],
            ['id' => 163, 'nombre' => 'Medidor de halo de inhibición'],
            ['id' => 164, 'nombre' => 'Medidor de punto de fusion'],
            ['id' => 165, 'nombre' => 'Mezclador de tambores'],
            ['id' => 166, 'nombre' => 'Mezcladora'],
            ['id' => 167, 'nombre' => 'Mezcladora 3D'],
            ['id' => 168, 'nombre' => 'Micropipeta'],
            ['id' => 169, 'nombre' => 'Micropipeta monocanal'],
            ['id' => 170, 'nombre' => 'Microscopio óptico'],
            ['id' => 171, 'nombre' => 'Molino'],
            ['id' => 172, 'nombre' => 'Molino a bolas'],
            ['id' => 173, 'nombre' => 'Molino a martillo'],
            ['id' => 174, 'nombre' => 'Molino Calibrador'],
            ['id' => 175, 'nombre' => 'Molino Calibrador Conico'],
            ['id' => 176, 'nombre' => 'Molino coloidal'],
            ['id' => 177, 'nombre' => 'Molino de martillos'],
            ['id' => 178, 'nombre' => 'Molino de pantalla cónica'],
            ['id' => 179, 'nombre' => 'Molino oscilante'],
            ['id' => 180, 'nombre' => 'Mortero'],
            ['id' => 181, 'nombre' => 'Muestreador de aire comprimido y gases'],
            ['id' => 182, 'nombre' => 'Muestreador de aire volumetrico'],
            ['id' => 183, 'nombre' => 'Muestreador de aire y gases / RCS High Flow'],
            ['id' => 184, 'nombre' => 'Mufla'],
            ['id' => 185, 'nombre' => 'Osmómetro'],
            ['id' => 186, 'nombre' => 'Ovulera'],
            ['id' => 187, 'nombre' => 'Paila'],
            ['id' => 188, 'nombre' => 'Paila de Recubrimiento'],
            ['id' => 189, 'nombre' => 'Pantalla'],
            ['id' => 190, 'nombre' => 'Pass trough'],
            ['id' => 191, 'nombre' => 'PHmetro'],
            ['id' => 192, 'nombre' => 'Phmetro portatil'],
            ['id' => 193, 'nombre' => 'Plancha a vapor'],
            ['id' => 194, 'nombre' => 'Plancha calefactora'],
            ['id' => 195, 'nombre' => 'Plataforma para elevador'],
            ['id' => 196, 'nombre' => 'Polarímetro'],
            ['id' => 197, 'nombre' => 'Portafiltro'],
            ['id' => 198, 'nombre' => 'Precintadora'],
            ['id' => 199, 'nombre' => 'Pulmón'],
            ['id' => 200, 'nombre' => 'Pulmón de aire comprimido'],
            ['id' => 201, 'nombre' => 'Punto de Fusión'],
            ['id' => 202, 'nombre' => 'Purificador de Agua'],
            ['id' => 203, 'nombre' => 'Reactor'],
            ['id' => 204, 'nombre' => 'Recipiente acero inoxidable'],
            ['id' => 205, 'nombre' => 'Recipiente de acero inoxidable'],
            ['id' => 206, 'nombre' => 'Recipiente de vidrio'],
            ['id' => 207, 'nombre' => 'Refractómetro'],
            ['id' => 208, 'nombre' => 'Refrigerador'],
            ['id' => 209, 'nombre' => 'Roscadora semiautomática'],
            ['id' => 210, 'nombre' => 'Rotogranulador'],
            ['id' => 211, 'nombre' => 'Secador de lecho fluidizado'],
            ['id' => 212, 'nombre' => 'Secarropas'],
            ['id' => 213, 'nombre' => 'Sellador'],
            ['id' => 214, 'nombre' => 'Sellador manual'],
            ['id' => 215, 'nombre' => 'Sellador para Termocontraible'],
            ['id' => 216, 'nombre' => 'Selladora de bolsas'],
            ['id' => 217, 'nombre' => 'Selladora de polietileno'],
            ['id' => 218, 'nombre' => 'Selladora de pomos'],
            ['id' => 219, 'nombre' => 'Sensores contadores de partículas'],
            ['id' => 220, 'nombre' => 'Sistema contador de partículas sector de Estériles'],
            ['id' => 221, 'nombre' => 'Sistema de brazo mecánico'],
            ['id' => 222, 'nombre' => 'Sistema de brazo robótico'],
            ['id' => 223, 'nombre' => 'Sistema de control y alarma'],
            ['id' => 224, 'nombre' => 'Sistema de esterilizado'],
            ['id' => 225, 'nombre' => 'Sistema de Generación de TyH de la cámaras de estabilidad'],
            ['id' => 226, 'nombre' => 'Sistema de prueba punto de burbuja'],
            ['id' => 227, 'nombre' => 'Sistema de refirgeración'],
            ['id' => 228, 'nombre' => 'Sistema de ventilación'],
            ['id' => 229, 'nombre' => 'Sopladora de frascos'],
            ['id' => 230, 'nombre' => 'Sprayador de alcohol'],
            ['id' => 231, 'nombre' => 'Tablero de la Red contra incendios'],
            ['id' => 232, 'nombre' => 'Tacómetro'],
            ['id' => 233, 'nombre' => 'Tamiz'],
            ['id' => 234, 'nombre' => 'Tamiz de Acero Inoxidable'],
            ['id' => 235, 'nombre' => 'Tanque'],
            ['id' => 236, 'nombre' => 'Tanque de acero inoxidable'],
            ['id' => 237, 'nombre' => 'Tanque (Cisterna Red de Incendios)'],
            ['id' => 238, 'nombre' => 'Tapadora'],
            ['id' => 239, 'nombre' => 'Tapadora automática'],
            ['id' => 240, 'nombre' => 'Termohigrómetro'],
            ['id' => 241, 'nombre' => 'Termometro'],
            ['id' => 242, 'nombre' => 'Termometro Datalogger'],
            ['id' => 243, 'nombre' => 'Termómetro de Hg'],
            ['id' => 244, 'nombre' => 'Termómetro de punción'],
            ['id' => 245, 'nombre' => 'Termometro digital'],
            ['id' => 246, 'nombre' => 'Termómetro infrarrojo'],
            ['id' => 247, 'nombre' => 'Termómetro varilla'],
            ['id' => 248, 'nombre' => 'Termotanque'],
            ['id' => 249, 'nombre' => 'Testeador de integridad de filtros'],
            ['id' => 250, 'nombre' => 'Titulador'],
            ['id' => 251, 'nombre' => 'TOC Online'],
            ['id' => 252, 'nombre' => 'Torquímetro'],
            ['id' => 253, 'nombre' => 'Turbomezclador Granulador'],
            ['id' => 254, 'nombre' => 'UTA C (Ampliación Sólidos, ala izquierda)'],
            ['id' => 255, 'nombre' => 'UTA D (Ampliación Sólidos, ala derecha)'],
            ['id' => 256, 'nombre' => 'UTA Desarrollo farmacéutico'],
            ['id' => 257, 'nombre' => 'UTA Ensobrado'],
            ['id' => 258, 'nombre' => 'UTA Esterilidad'],
            ['id' => 259, 'nombre' => 'UTA estufa de secado'],
            ['id' => 260, 'nombre' => 'UTA Lecho fluido'],
            ['id' => 261, 'nombre' => 'UTA LySS estériles'],
            ['id' => 262, 'nombre' => 'UTA LySS no estériles'],
            ['id' => 263, 'nombre' => 'UTA Microbiología general'],
            ['id' => 264, 'nombre' => 'UTA Paila de recubrimiento'],
            ['id' => 265, 'nombre' => 'UTA Paila de recubrimiento COMASA'],
            ['id' => 266, 'nombre' => 'UTA Pesadas y Muestreo'],
            ['id' => 267, 'nombre' => 'UTA Segregados'],
            ['id' => 268, 'nombre' => 'UTA Sólidos A'],
            ['id' => 269, 'nombre' => 'UTA Sólidos B'],
            ['id' => 270, 'nombre' => 'Vacuómetro'],
            ['id' => 271, 'nombre' => 'Varilla termómetro'],
            ['id' => 272, 'nombre' => 'Vibrador'],
            ['id' => 273, 'nombre' => 'Viscosímetro'],
            ['id' => 274, 'nombre' => 'Vórtex'],
            ['id' => 275, 'nombre' => 'Zorra'],
            ['id' => 276, 'nombre' => 'Mezclador multidireccional'],
            ['id' => 277, 'nombre' => 'Termocontraible'],
            ['id' => 278, 'nombre' => 'Balómetro'],
            ['id' => 279, 'nombre' => 'Contador de particulas portatil'],
            ['id' => 280, 'nombre' => 'Datalogger'],
            ['id' => 281, 'nombre' => 'Analizador de gases'],
            ['id' => 282, 'nombre' => 'Validador de Temperatura'],
            ['id' => 283, 'nombre' => 'Rugosímetro'],
            ['id' => 284, 'nombre' => 'Lavarropas automaticos'],
            ['id' => 285, 'nombre' => 'Termohigrómetro datalogger'],
            ['id' => 286, 'nombre' => 'Termómetro Datalogger'],
        ];

        DB::table('tipos_equipos')->insert($tipos);
    }
}
